version: '3'

services:
  backend-db:
    image: 'postgres:15'
    restart: unless-stopped
    ports:
      - "5432:5432"
    container_name: "service-db"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/test.sql
      - /root/db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5050:80"
    volumes:
      - /root/pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'service-backend'
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - backend-db
    volumes:
      - /root/user_avatars:/var/lib/image-data
      - /root/db-indexes:/var/lib/index_data

  frontend:
    build:
      context: ./MD-frontend
      dockerfile: Dockerfile
    restart: always
    container_name: 'service-frontend'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    volumes:
      - /root/etc/ssl:/etc/ssl
      - web-root:/var/www/html

volumes:
  web-root:
