version: '3'

services:
  backend-db:
    image: 'postgres:15'
    restart: always
    ports:
      - "5432:5432"
    container_name: "database"
    environment:
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
      - "POSTGRES_DB=${PG_DB}"
    env_file:
      - .env
    volumes:
      - ./infrastructure/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5050:80"

    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: 'backend-app'
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - backend-db

volumes:
  db-data:
  pgadmin-data: