version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: "movies_diary_db"
    env_file:
      - vars.env

  backend:
    image: 'moviesdiary-backend'
    container_name: 'backend-app'
    env_file:
      - vars.env
    ports:
      - 8000:8000