version: '3'

services:
  backend-db:
    image: 'postgres:15'
    restart: always
    ports:
      - "5432:5432"
    container_name: "service-db"
    environment:
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
      - "POSTGRES_DB=${PG_DB}"
    env_file:
      - .env
    volumes:
      - ./infrastructure/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'service-backend'
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - backend-db
    volumes:
      - /c/Users/datfe/Pictures/service-images:/var/lib/image-data

  frontend:
    build:
      context: ./MD-frontend
      dockerfile: Dockerfile
    restart: always
    container_name: 'service-frontend'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - dhparam:/etc/ssl/certs

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email datfeelman@gmail.com --agree-tos --no-eff-email --force-renewal -d xn--b1abohqcebc.xn--p1ai


volumes:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/movieDiary/dhparam/
      o: bind
  image-data:
  db-data:
  pgadmin-data:
  web-root:
  certbot-etc:
  certbot-var:
