server:
  error:
    include-stacktrace: never

spring:
  datasource:
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    url: ${PG_DB}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      connection:
        auto-commit: false

jwt:
  secret-key: ${JWT_SECRET_KEY}

image-directory: "/var/lib/image-data"

x_api_key: ${X_API_KEY}
