server:
  error:
    include-stacktrace: never

spring:
  output:
  ansi:
    enabled: DETECT
  datasource:
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    url: ${PG_DB}

  jpa:
    hibernate:
      search:
        enabled: true
        backend:
          analysis:
            configurer: class:sobad.code.moviesdiary.hibernateSearch.MyAnalysisConfigurer
          type: lucene
          directory:
            root: "/var/lib/index_data"
      ddl-auto: update
      show-sql: false
      connection:
        auto-commit: false

jwt:
  secret-key: ${JWT_SECRET_KEY}

image-directory: "/var/lib/image-data"

x_api_key: ${X_API_KEY}

logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
