server:
  port: ${PORT:8000}
  http2:
    enabled: true

base-url: /api

springdoc:
  swagger-ui:
    path: /api-docs.html

jwt:
  secret-key: 'secret key'
  expiration: 1200
  refresh-token:
    expiration: 8400

x-api-key: "api-key"

spring:
  datasource:
    username: "username"
    password: "username"
    url: "db_url"

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
log4j:
  logger:
    org:
      hibernate:
        SQL: TRACE
        type: TRACE

logging:
  level:
    root: INFO
    web: INFO