spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: "datfeel"
    password: "asedur81"
    url: "jdbc:postgresql://localhost:5432/movies_diary"
    show-sql: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        search:
          enabled: true
          backend:
            analysis:
              configurer: class:sobad.code.moviesdiary.hibernateSearch.MyAnalysisConfigurer
            type: lucene
            directory:
              root: "C:\\Users\\datfe\\Pictures\\service-images"

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

jwt:
  secret-key: fdsflksdncvkjlsnadklvBJKASBVKJLBASDLJFNSDVBAJKhjfvsdhjfvashjbvjhcavsfdvdsKJSDLBAKOALknkdfsansakl

x_api_key: 1HKFM1Z-X6S4PW0-MWSCWN5-V80PF7Z

image-directory: "C:\\Users\\datfe\\Pictures\\service-images"

logging:
  level:
    root: INFO
    web: DEBUG