server:
  port: ${PORT:5000}
  http2:
    enabled: true

base-url: /api

springdoc:
  swagger-ui:
    path: /api-docs.html

jwt:
  secret-key: 'fdsflksdncvkjlsnadklvBJKASBVKJLBASDL'
  expiration: 1200
  refresh-token:
    expiration: 8400

x-api-key: 1HKFM1Z-X6S4PW0-MWSCWN5-V80PF7Z

spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./test"

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

logging:
  level:
    root: INFO
    web: DEBUG