spring:
  datasource:
    username: " "
    password: " "
    url: "jdbc:h2:./test"
    show-sql: true

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

jwt:
  secret-key: fdsflksdncvkjlsnadklvBJKASBVKJLBASDLJFNSDVBAJKhjfvsdhjfvashjbvjhcavsfdvds

x_api_key: 1HKFM1Z-X6S4PW0-MWSCWN5-V80PF7Z

logging:
  level:
    root: INFO
    web: DEBUG