server:
  port: 8000
  http2:
    enabled: true

base-url: /api
spring:
  application:
    name: movies_diary
  profiles:
    active: prod

jwt:
  expiration: 24

springdoc:
  swagger-ui:
    path: /api-docs.html

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
