server:
  error:
    include-stacktrace: never

spring:
  datasource:
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    url: ${PG_DB}

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: false
      connection:
        auto-commit: false

jwt:
  secret-key: ${JWT_SECRET_KEY}

x_api_key: ${X_API_KEY}